Test5: Time.o Timing.o Event.o Test5.o Professor.o Group.o Classroom.o schedulable.o Exception.o TimeException.o TimingException.o
	g++ -o Test5 Time.o Timing.o Event.o Professor.o Group.o Classroom.o schedulable.o Exception.o TimeException.o TimingException.o Test5.o
	
Time.o: Time.cpp Time.h
	g++ -c Time.cpp -o Time.o

Timing.o: Timing.cpp Timing.h
	g++ -c Timing.cpp -o Timing.o

Event.o: Event.cpp Event.h
	g++ -c Event.cpp -o Event.o

Professor.o: Professor.cpp Professor.h
	g++ -c Professor.cpp -o Professor.o

Group.o: Group.cpp Group.h
	g++ -c Group.cpp -o Group.o

Classroom.o: Classroom.cpp Classroom.h
	g++ -c Classroom.cpp -o Classroom.o

schedulable.o: schedulable.cpp schedulable.h
	g++ -c schedulable.cpp -o schedulable.o

Exception.o: Exception.cpp Exception.h
	g++ -c Exception.cpp -o Exception.o

TimeException.o: TimeException.cpp TimeException.h
	g++ -c TimeException.cpp -o TimeException.o

TimingException.o: TimingException.cpp TimingException.h
	g++ -c TimingException.cpp -o TimingException.o

Test5.o: Test5.cpp
	g++ -c Test5.cpp -o Test5.o
