Test3: Time.o Timing.o Event.o Test3.o 
	g++ -o Test3 Time.o Timing.o Event.o Test3.o
Time.o: Time.cpp Time.h
	g++ -c Time.cpp -o Time.o

Timing.o: Timing.cpp Timing.h
	g++ -c Timing.cpp -o Timing.o

Event.o: Event.cpp Event.h
	g++ -c Event.cpp -o Event.o

Test3.o: Test3.cpp
	g++ -c Test3.cpp -o Test3.o
