Test4: Time.o Timing.o Event.o Test4.o Professor.o
	g++ -o Test4 Time.o Timing.o Event.o Professor.o Test4.o
	
Time.o: Time.cpp Time.h
	g++ -c Time.cpp -o Time.o

Timing.o: Timing.cpp Timing.h
	g++ -c Timing.cpp -o Timing.o

Event.o: Event.cpp Event.h
	g++ -c Event.cpp -o Event.o

Professor.o: Professor.cpp Professor.h
	g++ -c Professor.cpp -o Professor.o

Test4.o: Test4.cpp
	g++ -c Test4.cpp -o Test4.o
