Test2: Time.o Timing.o Event.o Test2.o
	g++ -o Test2 Time.o Timing.o Event.o Test2.o

Time.o: Time.cpp Time.h
	g++ -c Time.cpp -o Time.o

Timing.o: Timing.cpp Timing.h
	g++ -c Timing.cpp -o Timing.o

Event.o: Event.cpp Event.h
	g++ -c Event.cpp -o Event.o
	
Test2.o: Test2.cpp
	g++ -c Test2.cpp -o Test2.o
